name: Docker build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and test Comby using Docker image
        run: docker build . -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" -e PULL_REQUEST_NUMBER="$PULL_REQUEST_NUMBER" --file Dockerfile --tag test-build:$(date +%s)
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
