name: Docker build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Comby Docker image
        run: docker build . --file Dockerfile --tag test-build:latest
      - name : Get CodeCov env
        run: ci_env=`bash <(curl -s https://codecov.io/env)`
      - name: Run Comby tests
        run: docker run $ci_env test-build:latest /bin/bash -c "opam exec -- make build-with-coverage && opam exec -- dune runtest --instrument-with bisect_ppx --force && ./push-coverage-report.sh"

